version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgressql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_PASSWORD=password
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABSE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=password

    ports:
      - 8889:8080
      - 8443:8443
    depends_on:
      - postgres
  nginx:
    image: nginx
    container_name: nginx
    network_mode: "host" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./localhost.crt:/etc/nginx/localhost.crt:ro
      - ./localhost.key:/etc/nginx/localhost.key:ro
    ports:
      - 5002:5002
      - 8888:8888
      - 8890:8443
      - 80:80
      - 443:443
    depends_on:
      - keycloak
volumes:
  postgres_data:
    driver: local
    